/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "nitrite-java"

include(
    ":nitrite-mvstore-adapter",
    ":potassium-nitrite",
    ":nitrite-spatial",
    ":nitrite-support",
    ":nitrite-jackson-mapper",
    ":nitrite-rocksdb-adapter",
    ":nitrite",
)