/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.freefair.lombok") version "8.6"
}

dependencies {
    api(projects.nitrite)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.locationtech.jts.jts.core)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    testImplementation(libs.junit.junit)
    testImplementation(projects.nitriteMvstoreAdapter)
    testImplementation(libs.org.apache.logging.log4j.log4j.api)
    testImplementation(libs.org.apache.logging.log4j.log4j.slf4j2.impl)
    testImplementation(libs.org.apache.logging.log4j.log4j.core)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Nitrite Spatial"

java {
    withJavadocJar()
}
